function(enable_warnings TARGET)
    if (MSVC)
        target_compile_options(${TARGET} PRIVATE /W4)
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
        target_compile_options(${TARGET} PRIVATE -pedantic-errors -Wall -Wextra -Wconversion -Wsign-conversion)
    endif ()
endfunction()

function(treat_warnings_as_errors TARGET)
    if (MSVC)
        target_compile_options(${TARGET} PRIVATE /WX)
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
        target_compile_options(${TARGET} PRIVATE -Werror)
    endif ()
endfunction()